parameters:
    egzakt_doctrine_behaviors.translatable.listener.current_locale_callable.class: Egzakt\DoctrineBehaviorsBundle\ORM\Translatable\CurrentLocaleCallable
    egzakt_doctrine_behaviors.translatable.listener.class:                         Egzakt\DoctrineBehaviorsBundle\ORM\Translatable\TranslatableListener
    egzakt_doctrine_behaviors.sluggable.listener.class:                            Egzakt\DoctrineBehaviorsBundle\ORM\Sluggable\SluggableListener
    egzakt_doctrine_behaviors.uploadable.listener.class:                           Egzakt\DoctrineBehaviorsBundle\ORM\Uploadable\UploadableListener

services:
    egzakt_doctrine_behaviors.uploadable.listener:
        class: %egzakt_doctrine_behaviors.uploadable.listener.class%
        arguments: [%egzakt_doctrine_behaviors.uploadable.upload_root_dir%]
        public:  false
        tags:
            - { name: doctrine.event_subscriber }

    egzakt_doctrine_behaviors.translatable.listener.current_locale_callable:
        class: "%egzakt_doctrine_behaviors.translatable.listener.current_locale_callable.class%"
        arguments: [@service_container] # lazy request resolution
        public:  false

    egzakt_doctrine_behaviors.translatable.listener:
        class:   %egzakt_doctrine_behaviors.translatable.listener.class%
        arguments: [@egzakt_doctrine_behaviors.translatable.listener.current_locale_callable]
        public:  false
        tags:
            - { name: doctrine.event_subscriber }
